#!/bin/bash
# Package Rename Summary
# ultrasonic_bridge → robot_sensors

echo "=========================================="
echo " Package Renamed Successfully!"
echo "=========================================="
echo ""
echo "OLD NAME: ultrasonic_bridge"
echo "NEW NAME: robot_sensors"
echo ""
echo "REASON: Package now handles ALL robot sensors:"
echo "  • 5x Ultrasonic sensors (HC-SR04)"
echo "  • 8x IR sensors (4 obj + 4 stair)"
echo "  • 2x Wheel encoders"
echo "  • 4x Motor PWM outputs"
echo "  • LIDAR integration"
echo ""
echo "UPDATED FILES:"
echo "  ✓ package.xml"
echo "  ✓ setup.py"
echo "  ✓ setup.cfg"
echo "  ✓ launch files"
echo "  ✓ scripts"
echo "  ✓ documentation"
echo ""
echo "NEW COMMANDS:"
echo "  ros2 launch robot_sensors robot_launch.py"
echo "  ros2 run robot_sensors multi_sensor_node"
echo "  ros2 run robot_sensors serial_range_node"
echo ""
echo "STATUS: ✅ Package built and ready!"
echo "=========================================="
